### ISSUE TITLE
Magic Tags based on values of text fields don't work for hidden field or variables

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#375]
Using [this form](http://pastebin.com/Gg7y3rJH) I would expect the hidden fields set form text fields and variables, and hidden fields set from the variables to track the values of the text fields.

In 1.3.2 they do not, but the value of the magic tag does render in the HTML field.

In current-dev the do not and the value of the magic tags do not render in HTML field.

**Comment by Desertsnowman** [comment]
Wow that's a big issue. Ye I'll sort that in the morning. Going to try get a temporary mobile Internet package.

**Comment by Desertsnowman** [comment]
Variables wont sync since they are intended for use in processors and server side actions. But I have added field syncing to hidden fields

**Comment by Shelob9** [comment]
Reopening. Using the form I linked to when opening this issue, magic tags populate hidden fields but not variables

**Comment by Desertsnowman** [comment]
@Shelob9 as I mentioned in my last comment, variables are not intended for front end binding. they are values to use within processing and auto values on submission. This is because they can use combined processor data like processor return values. E.g returning the user ID from the register user processor. this data is only available after processing.
