### ISSUE TITLE
New processor insert/update thing is totally broken with Stripe

### ISSUE THREAD

**Issue by Shelob9** [Desertsnowman/Caldera-Forms#412]
I think this is beacuse the elements are not in the DOM when the form loads. This causes JavaScript to fail so hard that the form can not update, so settings are lost on refresh. Not sure what the point of this feature is, I don't know when it got added, but I think best solution is to revert it.
![default](https://cloud.githubusercontent.com/assets/1994311/12571795/c7d76dea-c3b2-11e5-8256-81901779c9f3.png)

**Comment by Desertsnowman** [comment]
Doubtful the insert/update is the cause. its purely just a toggle input and has nothing to do with elements being in the DOM.
And I told you about it on the 3rd of December along with a screenshot.

I'm not removing it since it's needed for entry editing. Without it all processors will run when updating an entry, unless specified to run on update.

Can you please add a few steps on how to replicate this? I tried by adding just the Stripe processor but I don't get the same result.
