### ISSUE TITLE
Virus in fields.min.js

### ISSUE THREAD

**Issue by mn628** [Desertsnowman/Caldera-Forms#414]
Every time my host scans my site they block my port 80/443 due to this plugin, they say it contains virus. Please take a look at this forms fields.min.js (or may be something else file). Please solve this problem fast.
Other Issues.
* When pressed back/previous button in a form it wants you to fill the form on current page.
* Unable to set length of a text field.
* Condition logic doesn't work for date, I mean if the date like 01-02-2016 and compared with 05-01-2016 it will say 05-01-2016 is greater.

Although I love this plugin and completely understand that it takes time to fix bugs but please take a look at virus bug fast.

**Comment by Desertsnowman** [comment]
First off, thanks for providing feedback. It truly is appreciated!

Second: there is no virus, it's most likely a false positive. a basic word search in the "scanner" looking for things like `eval` or `base64` or what ever they deem necessary. Basically, the `fields.min.js` is code I wrote, and saying the code is a virus is giving me way too much credit. I'm just not that good.
Basically, I can't fix the bug since it's not a bug but an over zealous host, setting a scanner to 0. I think the best solution here would be to ask them to set an exception on the file.

Conditional logic on dates. This is something I have been planning and hope to make progress soon. I find working with dates tricky but will keep working on it.
Field length: also a feature I have been wanting to add. Hopefully I'll get it in sooner than later.
back/previous : if a field is required, you'll need to fill it in before you can progress. that's just how required fields work. Unless I misunderstood what you meant.
