### ISSUE TITLE
Submitted Forms not showing in Admin Panel

### ISSUE THREAD

**Issue by jaimeadvantageousmediapartners** [Desertsnowman/Caldera-Forms#520]
When trying to view a submitted form entry in the admin panel, box is blank, showing only green bar with entry #, and X button. White area blank, bottom shows blue edit entry button and close button. When edit entry button pressed, info comes up with the following, as well as the information:

Warning: Illegal string offset 'opt1825496' in /home3/garytoll/public_html/biz-e-book.com/wp-content/plugins/caldera-forms/classes/core.php on line 4037

Warning: Illegal string offset 'opt1446427' in /home3/garytoll/public_html/biz-e-book.com/wp-content/plugins/caldera-forms/classes/core.php on line 4037

Warning: Illegal string offset 'opt1874338' in /home3/garytoll/public_html/biz-e-book.com/wp-content/plugins/caldera-forms/classes/core.php on line 4037

Warning: Illegal string offset 'opt1765351' in /home3/garytoll/public_html/biz-e-book.com/wp-content/plugins/caldera-forms/classes/core.php on line 4037

**Comment by Shelob9** [comment]
@jaimeadvantageousmediapartners Thanks for the report, this is an important bug we are working on. I am closing this as a duplicate of #508 since that was the first report.

The entries should be saving fine, so once we get a fix in, hopefully next week, you will be fine.

BIG QUESTION: Did you change any options for any of your options in a select field of this form at any point?

**Comment by jaimeadvantageousmediapartners** [comment]
No, didn’t make any changes after form was made. Thanks for your speedy answer :)

**Comment by Shelob9** [comment]
Thanks for that info @jaimeadvantageousmediapartners This is going to be one of my next week priorities.
