### ISSUE TITLE
Issue: Scroll to required/error field with sticky header themes

### ISSUE THREAD

**Issue by brandbrilliance** [Desertsnowman/Caldera-Forms#521]
Certain themes allow for a sticky header. However, when you have an error or incomplete required field and the script scrolls to that field, it may end up below the sticky theme header. Perhaps there could be an offset of some kind to allow for this? Or at least provide some code on how one might be able to "fix" this situation. Otherwise a user keeps complaining that when they click the submit "nothing happens" even though the page did scroll, but the error/message/required is actually hidden behind the stick top header.

**Comment by Shelob9** [comment]
@brandbrilliance This is a support question, not a bug as it has to do with integration with specific themes. Can you please open a support ticket at https://CalderaWP.com/support and let us know what theme you are using?

**Comment by jcvanhalle-ec** [comment]
If anyone is still looking for a general fix here's what I did:

1. Uncheck the `scroll to the top after submission` option in the form setting
2. Enable a callback function to be called after form submission in the form setting and name it `scrollToTheTop`
3. Enqueue that function (either globally on on the page displaying the form):
```javascript
  const scrollToTheTop = () => {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
```

Depending on how your sticky menu is behaving or where your notice is being displayed on the page you may need to jump to an hidden element instead of the top.
