### ISSUE TITLE
Make recaptchas required with styling to show if not completed

### ISSUE THREAD

**Issue by mozzarella85** [Desertsnowman/Caldera-Forms#562]
Hi, 

The reCAPTCHA field is labeled as required, but if not completed, the form still sends with no error message or styling indicating that the reCAPTCHA to be completed.

Thanks

**Comment by Shelob9** [comment]
We are slowly phasing out the recpatchas beacuse they are not needed for anti-spam -- the default honey pot is more effective and are bad for conversions. Also, we are about to start a major effor=t ot improve accessibility.

Currently recapthas are purely cosmetic and are not validated, since the honeypot still works, this makes anti-spam more effective. We are worried about changes in layout if they are removed from the form that is the main reason they are still there. We don't have a good system for that yet but I am thinking on it for the next release, see #570
